name: Compress images

on: pull_request

jobs:
  compress-images:
    name: Try to optimize repo image files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Optimize with Calibre's image actions
        uses: docker://calibreapp/github-image-actions@sha256:23bdfdb399f490dacc86c88cc79c391d76e7ffc1781db586cb28b36b7ca98fb7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
