name: Lighthouse

on:
  pull_request:
    types: [labeled]
    branches:
      - master

jobs:
  lighthouse:
    name: Audit site using Lighthouse
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'lighthouse')

    steps:
      - name: Test Netlify deploy preview
        uses: treosh/lighthouse-ci-action@v11
        env:
          HOST_BASE: storefront-template.netlify.com
          HOST_PREVIEW: deploy-preview-${{ github.event.pull_request.number }}--storefront-template.netlify.com
        with:
          urls: |
            https://$HOST_BASE/
            https://$HOST_PREVIEW/
            https://$HOST_BASE/slug
            https://$HOST_PREVIEW/slug
            https://$HOST_BASE/app/
            https://$HOST_PREVIEW/app/

      - name: Save report artifact
        uses: actions/upload-artifact@v2
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          name: lighthouse-results
          path: '.lighthouseci'
