name: Publish

on: registry_package

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    env:
      PKG_OWNER: ${{ github.event.registry_package.owner.login }}
      PKG_NAME: ${{ github.event.registry_package.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm i

      - name: Build package
        run: npx lerna run --scope=@$PKG_OWNER/$PKG_NAME build

      - name: Edit package.json and publish to npm registry
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./@$PKG_OWNER/$PKG_NAME && \
          node -p "const pkg = require('./package.json'); \
          if (pkg.publishConfig) delete pkg.publishConfig.registry; \
          JSON.stringify(pkg, null, 2)" > pkg.json && mv pkg.json package.json && \
          npm publish --access public

      - name: Trigger Netlify deploy
        if: github.event.registry_package.name == 'storefront-template'
        env:
          NETLIFY_HOOK_ENDPOINT: ${{ secrets.NETLIFY_HOOK_ENDPOINT }}
        run: |
          sleep 30
          curl -X POST -d {} $NETLIFY_HOOK_ENDPOINT
